version: '3.9'

services:
  dev:
    image: sehandev/dongan-youth
    ports:
      - 3001:3000
    volumes:
      - .:/workspace
      - /etc/ORACLE/WALLETS/affiliation:/etc/ORACLE/WALLETS/affiliation
    working_dir: /workspace
    command: sh -c "
      yarn set version stable &&
      yarn &&
      yarn dev"
    environment:
      - TNS_ADMIN=/etc/ORACLE/WALLETS/affiliation
      - NODE_PATH=`npm root -g`
  prod:
    image: sehandev/dongan-youth
    ports:
      - 3001:3000
    volumes:
      - .:/workspace
      - /etc/ORACLE/WALLETS/affiliation:/etc/ORACLE/WALLETS/affiliation
    working_dir: /workspace
    command: sh -c "
      yarn set version stable &&
      yarn &&
      yarn build &&
      yarn start"
    environment:
      - TNS_ADMIN=/etc/ORACLE/WALLETS/affiliation
      - NODE_PATH=`npm root -g`
