version: '3.9'

services:
  dev:
    image: sehandev/dongan-youth:arm
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: sh -c "pnpm install && pnpm dev"
    restart: always
    network_mode: 'host'
  prod:
    image: sehandev/dongan-youth:arm
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: sh -c "pnpm install && pnpm build && pnpm start"
    restart: always
    network_mode: 'host'
