version: '3.9'

services:
  dev:
    image: sehandev/dongan-youth:arm
    volumes:
      - .:/workspace
      - /opt/oracle/instantclient_19_10/network/admin:/opt/oracle/admin
    working_dir: /workspace
    command: sh -c "yarn && yarn dev"
    network_mode: 'host'
  prod:
    image: sehandev/dongan-youth:arm
    volumes:
      - .:/workspace
      - /opt/oracle/instantclient_19_10/network/admin:/opt/oracle/admin
    working_dir: /workspace
    command: sh -c "yarn && yarn build && yarn start"
    restart: always
    network_mode: 'host'
