version: '3.9'

services:
  dev:
    image: sehandev/dongan-youth:arm
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: sh -c "corepack prepare pnpm@8.4.0 --activate && pnpm install && pnpm dev"
    restart: always
    network_mode: 'host'
    environment:
      - TZ=Asia/Seoul
  prod:
    image: sehandev/dongan-youth:arm
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: sh -c "corepack prepare pnpm@8.4.0 --activate && pnpm install && pnpm build && pnpm start"
    restart: always
    network_mode: 'host'
    environment:
      - TZ=Asia/Seoul
